- README.md
- bundle.yaml
- overlays/offers-overlay.yaml
- overlays/storage-small-overlay.yaml
* Add default overlays for offers and a small storage setup
* Mark the charms as trusted (to actually be trusted it required the Juju admin to pass `--trust` to `juju deploy`)
* Additional documentation for how to deploy
> Add default overlays for offers and storage, add trust

- tests/integration/helpers.py
This change was triggered by a [failed alertmanager integration](https://github.com/sed-i/alertmanager-operator/runs/3799447023?check_suite_focus=true) test.
> increase timeout for integration test

- README.md
- tox.ini
~~Linking to the gh page rather than the raw. Links to raw are in just below in the example.~~ Linking to raw.
> use full url for overlays so they don't break on charmhub

- bundle.yaml.j2
- tests/integration/helpers.py
- tests/integration/test_bundle.py
- tox.ini
This PR adds an itest that addresses https://github.com/canonical/prometheus-k8s-operator/pull/239:
Now that `juju_unit` is no longer added to rule files, this test confirms that alerts still fire per unit (not only from the leader unit), and are correctly labeled as such.
> Add itest for multi unit alerts

- tests/integration/helpers.py
- tests/integration/test_bundle.py
This PR adds an itest that verifies all bundle charms can handle a frequent update-status emission.
Crossref: OPENG-687
> Add update-status itest

- .github/workflows/ci.yaml
Stable does not exist yet, which cause itests to fail and abort.
Run against beta instead of stable.
Run the integration tests.
Run scheduled tests against beta instead of stable.
> Run itests against beta, not stable

- bundle.yaml.j2
- tests/integration/test_bundle.py
This PR adds new self-monitoring and dashboards relations:
```yaml
- - grafana:grafana-source
- alertmanager:grafana-source
- - alertmanager:self-metrics-endpoint
- prometheus:metrics-endpoint
- - loki:metrics-endpoint
- prometheus:metrics-endpoint
- - loki:grafana-dashboard
- grafana:grafana-dashboard
- - prometheus:grafana-dashboard
- grafana:grafana-dashboard
- - alertmanager:grafana-dashboard
- grafana:grafana-dashboard
```
Deploy this bundle, and check:
- There are Alertmanager, Prometheus, and Loki Datasources
- There are Alertmanager, Prometheus, and Loki Dashboards
> Self monitoring relations

- .gitignore
- bundle.yaml.j2
- tox.ini
> ### ⚠️ Depends on other PRs 
>
> Do not merge this until https://github.com/canonical/alertmanager-k8s-operator/pull/101 is merged.
Add catalogue to the bundle.
Add deployment, configuration, and relations for the catalogue charm.
Once merged, a new bundle needs to be deployed.
- Render bundle
- Deploy bundle
- Access the catalogue on port 80
- Make sure all entries are there with sane details
Add service catalogue to bundle
> add catalogue

- INTEGRATING.md
- bundle.yaml.j2
Alertmanager was not ingressed, making it's UI inaccessible from outside of the cluster.
Add an ingress relation to the bundle
N/A
- Deploy bundle
- Access the catalogue
- Navigate using the link provided by the UI
Add ingress relation for Alertmanager
> Add ingress for Alertmanager

- bundle.yaml.j2
- When taking charms from local path, all images were pointing to latest rather than charms' `upstream-source`.
- When taking grafana from local path, resources list was missing `litestream`
Pin bundle images to charms' upstream-source.
NTA.
Deploy the bundle.
Pin bundle images to charms' upstream-source.
> Pin bundle images to charms' upstream-source

- tests/integration/helpers.py
- tests/integration/test_bundle.py
This addresses the first part of https://github.com/canonical/loki-k8s-operator/issues/211.
This PR adds an integration test to make sure Prometheus is correctly scraping Loki when Loki is behind traefik.
> add test to check prometheus scraping loki through traefik

- .github/workflows/ci.yaml
Before this PR, a scheduled CI failed all steps because the workflow first attempts to run the tests on the "beta" channel.
This PR changes the order a bit, so that the edge channel is tested first.
This way, when reviewing failed CI runs it would be more obvious when edge passes but the others fails.
The PR also adds steps to run scheduled CI on the other channels (candidate and stable).
NTA.
- Make sure CI passes for edge.
Always run edge itests first.
> Always run edge itests first

- .github/workflows/ci.yaml
- .github/workflows/matrix.yaml
Currently,
- Scheduled CI fails if any channel fails, because steps are sequential.
- Only testing for juju 2.9.34.
Add matrix tests and split out the scheduled event from the PR/push events.
Fixes #59.
Ref: [Expanding or adding matrix configurations](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations)
NTA.
Make sure all intended matrix items run.
Add scheduled integration matrix in separate workflow.
> Add scheduled integration matrix in separate workflow

- .github/workflows/matrix.yaml
A new minor version of juju is out and we need to itest on it.
- Add Juju 3.1.0 to the matrix test
- Keep 3.0.2 for now. We need to know if we'd need to exclude it in our `assumes` sections.
- Shorten job name so matrix params are visible in the sidebar
Add Juju 3.1.0 to the matrix test
> Add Juju 3.1.0 to the matrix test

- tests/load/gcp/prom-query/README.md
- tox.ini
Latest pylibjuju [dropped support](https://github.com/juju/python-libjuju/pull/774) for Juju 2.9.
As a result, the matrix tests now fail on Juju 2.9.
As we transition from Juju 2.9 to 3, pin pylibjuju to 3.0.x, which supports both 2.9 and 3.
> the approach we will follow is to use the latest python-libjuju that matches the juju release (2.9.38.1 -> 2.9.38, 3.1.0.1 -> 3.1.0)
>
> -- @juanmanuel-tirado 
> Juju API Server maintains compatibility within a major series.
So if we release an API method with 3.0, then we will continue to allow you to make that request with Juju 3.1, or 3.2, etc.
However, it is fairly clear that a 3.0 candidate won't know how to do things that we introduced in 3.1 (eg user secrets when they land in 3.2 will only be supported by pylibjuju-3.2+)
> 
> Across a major …
> Pin pylibjuju to 3.0.x

- pyproject.toml
- tests/integration/test_bundle.py
- tests/load/gcp/plot.py
- tox.ini
The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being one new rule being ignored (which wasn't checked before anyway): 
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.
> use ruff instead of flake8

- .github/workflows/matrix.yaml
- tests/integration/test_bundle.py
Matrix tests for Juju 2.9 [fail](https://github.com/canonical/cos-lite-bundle/actions/runs/5406674418/jobs/9823830823) for:
```
File "/home/runner/work/cos-lite-bundle/cos-lite-bundle/tests/integration/test_bundle.py", line 190, in test_prometheus_scrapes_loki_through_traefik
assert (f"/{ops_test.model.name}-loki-0/metrics", "up") in targets_summary
AttributeError: 'Model' object has no attribute 'name'
```
This is because [`Model.name` is not available in v2.9](https://github.com/juju/python-libjuju/issues/893).
- Use [`ops_test.model_name`](https://github.com/charmed-kubernetes/pytest-operator/blob/main/docs/reference.md#model_name) instead.
- Dump logs so we have further insight into https://bugs.launchpad.net/bugs/2025411
NTA.
`tox -e integration` with Juju 2.9.
Fix itest so it's …
> [itest] Use model_name instead of model.name

- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/matrix.yaml
- CONTRIBUTING.md
- README.md
- bundle.yaml.j2
- overlays/testing-overlay.yaml
- overlays/tls-overlay.yaml
- tests/e2e/test_machine_agent.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/test_bundle.py
- tox.ini
This PR adds a TLS overlay.
Fixes #78.
Depends on:
- https://github.com/canonical/traefik-k8s-operator/pull/204
- https://github.com/canonical/catalogue-k8s-operator/issues/31
- https://github.com/canonical/alertmanager-k8s-operator/issues/189
- https://github.com/canonical/prometheus-k8s-operator/issues/511
- https://github.com/canonical/grafana-k8s-operator/pull/257
- https://github.com/canonical/prometheus-k8s-operator/pull/524
- https://github.com/canonical/alertmanager-k8s-operator/pull/191
- https://github.com/canonical/traefik-k8s-operator/pull/245
- https://github.com/canonical/observability-libs/pull/60
- https://github.com/canonical/tls-certificates-interface/pull/74
- https://github.com/canonical/traefik-k8s-operator/pull/249
- …
> Add tls overlay

- overlays/three-nodes-overlay.yaml
- render_bundle.py
- tests/manual/README.md
- tests/manual/microk8s-ha.yaml
We need a reference deployment for testing a clustered COS.
This PR adds:
```mermaid
graph LR
subgraph microk8s-ha multipass VM
subgraph node-0 multipass VM
microk8s_0[microk8s]
end
subgraph node-1 multipass VM
microk8s_1[microk8s]
end
subgraph node-2 multipass VM
microk8s_2[microk8s]
end
juju
end
```
As of now, I am unaware of any readily deployable environment with such a setup. We (the o11y team) intend to use this as a baseline for a reference deployment of COS Lite.
A microk8s controller and an empty juju model are created as part of the cloud-init script so you can `juju deploy` right away. [Example](https://discourse.charmhub.io/t/pod-priority-and-affinity-in-juju-charms/4091/13).
Manually tested restarting the inner and outer VMs.
References:
- …
> Add cloud-init script for a 3-node microk8s ha cluster

- pyproject.toml
- tox.ini
Fix:
* Lint warnings
* Update to "ruff check" syntax ([example](https://github.com/canonical/cos-lite-bundle/actions/runs/10477442631/job/29018544646#step:5:143))
> Fix Lint errors and Warnings
